---
title: "Data can be a Drag!"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 100)

library(tidyverse) 
library(DBI)
library(glue)
library(here)
library(flexdashboard)
# Interactive way to plot things
library(esquisse)
library(ggThemeAssist)
library(miceadds)
library(rvest)
library(stringr)
library(plotly)
#source(here("Functions","db_helper_functions.R"))
# Default file type is .R  if different need to sepcify
source.all(here("Functions"))
```

```{r open the connection to dev db and get list of avail objects, echo=FALSE}
drag_conn <- rpdr_connection()

DBI::dbListTables(conn=drag_conn)

#DBI::dbDisconnect(drag_conn)
```
```{r get the views as dataframes, echo=FALSE, include=FALSE}
drag_conn <- rpdr_connection()

vw_contestants <- db_exec_param_query( db_conn=drag_conn
                                      , file_location = "SQL" 
                                      , file_name = "select_all.sql"
                                      , object_name="vw_contestants")

vw_mini_challenge <- db_exec_param_query( db_conn=drag_conn
                                      , file_location = "SQL" 
                                      , file_name = "select_all.sql"
                                      , object_name="vw_mini_challenge")

vw_episode_season_ratings <- db_exec_param_query( db_conn=drag_conn
                                      , file_location = "SQL" 
                                      , file_name = "select_all.sql"
                                      , object_name="vw_episode_season_ratings") %>% 
  mutate_at( "season_number"
            , list(~factor(.,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14")))
             )

vw_episodes <- db_exec_param_query( db_conn=drag_conn
                                      , file_location = "SQL" 
                                      , file_name = "select_all.sql"
                                      , object_name="vw_episodes")

DBI::dbDisconnect(drag_conn)
```

```{r Initialize esquisse to get a look at rating data, warning=FALSE}
esquisse::esquisser(vw_episode_season_ratings)

```

```{r Boxplots of viewership}
plotly::ggplotly(
  vw_episode_season_ratings %>%
   filter(season_number %in% c("9", "10", "11", "12", "13", "14")) %>%
   ggplot() +
    aes(
      x = season_number,
      y = viewer_count,
      colour = season_number
    ) +
    geom_boxplot(fill = "#112446") +
    scale_y_continuous(label=scales::comma_format())+
    scale_color_viridis_d(option = "viridis", direction = 1) +
    labs(
      x = "Season",
      y = "Viewers ",
      title = "Drag Race Viewership",
      subtitle = "Season 9 - 13"
    ) +
    theme_classic()
)
```

```{r views changing over time}
plotly::ggplotly(
  vw_episode_season_ratings %>%
   filter(season_number %in% c("9", "10", "11", "12", "13", "14")) %>%
   ggplot() +
    aes(
      x = episode_number,
      y = viewer_count
    ) +
    geom_line(size = 0.5) +
    scale_y_continuous(label=scales::comma_format())+
    labs(
      x = "Episode Number",
      y = "Viewers",
      title = "Season Viewership Trend"
    ) +
    theme_minimal() +
    facet_wrap(vars(season_number))
)
```

```{r}
plotly::ggplotly(
  vw_episode_season_ratings %>%
   filter(season_number %in% c("9", "10", "11", "12", "13", "14")) %>%
   ggplot() +
    aes(x = episode_number, y = viewer_rating) +
    geom_line(size = 0.5, colour = "#112446") +
    labs(
      x = "Episode Number",
      y = "Viewer Rating",
      title = "Season Rating Trend"
    ) +
    theme_minimal() +
    facet_wrap(vars(season_number))
)
```

